const VALID_ACTIONS = new Set([
  'DEFEND',
  'ATTACK_MOB',
  'EAT',
  'EQUIP',
  'FLY',
  'GET_ITEMS',
  'USE_ITEM',
  'USE_TRIDENT',
  'ENCHANT',
  'USE_ANVIL',
  'BUILD',
  'BREAK',
  'SLEEP',
  'USE_FURNACE',
  'CRAFT',
  'COLLECT',
  'ATTACK_PLAYER',
  'HELP_PLAYER',
  'SOCIAL',
  'EXPLORE',
  'TOGGLE_OFFHAND',
])

const STATIONARY_ACTIONS = new Set(['SLEEP', 'CRAFT', 'USE_FURNACE', 'ENCHANT', 'USE_ANVIL', 'BUILD', 'BREAK'])
const MOVEMENT_ACTIONS = new Set(['EXPLORE', 'HELP_PLAYER', 'COLLECT', 'FLY', 'DEFEND'])
const COMBAT_ACTIONS = new Set(['ATTACK_MOB', 'ATTACK_PLAYER', 'USE_TRIDENT'])

module.exports = {
  VALID_ACTIONS,
  STATIONARY_ACTIONS,
  MOVEMENT_ACTIONS,
  COMBAT_ACTIONS,
}
